# Generated by Django 4.2.1 on 2023-06-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudFunc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Studen',
        ),
    ]
