# Generated by Django 4.2.1 on 2023-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('assigned', models.CharField(max_length=30)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
